required = [
    "github.com/gin-gonic/gin",
    "github.com/hashicorp/go-cleanhttp",
    "github.com/json-iterator/go",
    "github.com/urfave/cli",
    "github.com/zsais/go-gin-prometheus",
]

[prune]
  go-tests = true
  unused-packages = true
